package ch.bfh.btx8081.w2013.red.GUI;

import java.util.Timer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ClassResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import ch.bfh.btx8081.w2013.red.Controller.NavigatorUI;

import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

/**
 * 
 * @author faton shabanaj
 * @email shabf2@bfh.ch
 * @version.nr 1.2
 *
 */
public class Login extends VerticalLayout implements View {

	final VerticalLayout layout;
	private AbsoluteLayout mainLayout;
	private HorizontalLayout horizontalLayout_1;
	private VerticalLayout upperVerticalLayout;
	private Button HelpButton;
	private Button HomeButton;
	private VerticalLayout verticalLayout_1;
	private PasswordField passwordField_1;
	private TextField textField_1;
	private MhcGuidDesign design;
	
	
	public Login() 
	
	{
		design = new MhcGuidDesign(this);
		layout = design.getLayout();
		mainLayout = design.getMainLayout();
		horizontalLayout_1 = design.getLowerHorizontalLayout();
		upperVerticalLayout = design.getUpperVerticalLayout();
		buildHorizontalLayout_1();
		createLayout();
	}

	private void createLayout() {

		design.setTitleLabel("Login");
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:60.0px;left:30.0px;");


	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub

	}
	

	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("260px");
		verticalLayout_1.setHeight("360px");
		verticalLayout_1.setMargin(false);

		// Logo which represents the mobile applicaton

		Embedded logo = new Embedded();
		logo.setImmediate(false);
		logo.setWidth("100%");
		logo.setHeight("160px");
		logo.setSource(new ThemeResource("Home.png"));
		logo.setType(1);
		logo.setMimeType("image/png");
		verticalLayout_1.addComponent(logo);

		// textField_1 for insert the Username
		
		textField_1 = new TextField(" Username:");
		textField_1.setImmediate(true);
		textField_1.setWidth("80%");
		textField_1.setHeight("-1px");
		verticalLayout_1.addComponent(textField_1);
		verticalLayout_1.setComponentAlignment(textField_1, Alignment.BOTTOM_CENTER);

		// passwordField_1 for insert the Password
		passwordField_1 = new PasswordField("Password: ");
		passwordField_1.setImmediate(false);
		passwordField_1.setWidth("80%");
		passwordField_1.setHeight("-1px");
		verticalLayout_1.addComponent(passwordField_1);
		verticalLayout_1.setComponentAlignment(passwordField_1, Alignment.MIDDLE_CENTER);
	
	
		return verticalLayout_1;
	}

	private void buildHorizontalLayout_1() {
		// common part: create layout

		// LoginButton
		HomeButton = new Button("Login");
		HomeButton.setImmediate(true);
		HomeButton.setWidth("-1px");
		HomeButton.setHeight("-1px");
		horizontalLayout_1.addComponent(HomeButton);
		horizontalLayout_1.setComponentAlignment(HomeButton, Alignment.MIDDLE_LEFT);

		// HelpButton
		HelpButton = new Button("   ?   ");
		HelpButton.setImmediate(true);
		HelpButton.setDescription(" Help-Mode ");
		HelpButton.setWidth("-1px");
		HelpButton.setHeight("22px");
		horizontalLayout_1.addComponent(HelpButton);
		horizontalLayout_1.setComponentAlignment(HelpButton, Alignment.MIDDLE_RIGHT);


	}

}


