package ch.bfh.btx8081.w2013.red.GUI;

import java.util.Timer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ClassResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import ch.bfh.btx8081.w2013.red.Controller.NavigatorUI;

import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

/**
 * 
 * @author shabf2 allererste Version
 * Autor Faton hochgeladen von Ivan wegen gitHub conflict 
 *
 */
public class Login extends VerticalLayout implements View {

	final Login layout;
	private AbsoluteLayout mainLayout;
	private HorizontalLayout horizontalLayout_1;
	private Button HelpButton;
	private Button HomeButton;
	private VerticalLayout verticalLayout_1;
	private Embedded logo;
	private Label NamederApp;
	private Button button_1;
	private PasswordField passwordField_1;
	private TextField textField_1;

	public Login() {
		this.layout = this;
		createLayout();
	}

	private void createLayout() {

		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("320px");
		mainLayout.setHeight("480px");

		// top-level component properties
		setWidth("320px");
		setHeight("480px");

		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:60.0px;left:30.0px;");

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:380.0px;left:0.0px;");

		layout.addComponent(mainLayout);
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub

	}

	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("260px");
		verticalLayout_1.setHeight("360px");
		verticalLayout_1.setMargin(false);

		// Logo which represents the mobile applicaton

		Embedded logo = new Embedded();
		logo.setImmediate(false);
		logo.setWidth("260px");
		logo.setHeight("150px");
		logo.setSource(new ThemeResource("Home.png"));
		logo.setType(1);
		logo.setMimeType("image/png");
		verticalLayout_1.addComponent(logo);

		// textField_1 for insert the Username
		textField_1 = new TextField();
		textField_1.setImmediate(true);
		textField_1.setWidth("80%");
		textField_1.setHeight("-1px");
		verticalLayout_1.addComponent(textField_1);
		verticalLayout_1.setComponentAlignment(textField_1, new Alignment(24));

		// passwordField_1 for insert the Password
		passwordField_1 = new PasswordField();
		passwordField_1.setImmediate(false);
		passwordField_1.setWidth("80%");
		passwordField_1.setHeight("-1px");
		verticalLayout_1.addComponent(passwordField_1);
		verticalLayout_1.setComponentAlignment(passwordField_1, new Alignment(
				48));

		// button_1 to which start the Event 'Login' and change the LoginView
		// with the'Home'-View.
		button_1 = new Button();
		button_1.setCaption("Login");
		button_1.setImmediate(false);
		button_1.setWidth("80%");
		button_1.setHeight("-1px");
		verticalLayout_1.addComponent(button_1);
		verticalLayout_1.setComponentAlignment(button_1, new Alignment(20));

		return verticalLayout_1;
	}

	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("320px");
		horizontalLayout_1.setHeight("100px");
		horizontalLayout_1.setMargin(false);

		// HomeButton
		HomeButton = new Button();
		HomeButton.setCaption("Button");
		HomeButton.setImmediate(true);
		HomeButton.setWidth("-1px");
		HomeButton.setHeight("-1px");
		horizontalLayout_1.addComponent(HomeButton);
		horizontalLayout_1.setComponentAlignment(HomeButton, new Alignment(48));

		// HelpButton
		HelpButton = new Button();
		HelpButton.setCaption("  ?  ");
		HelpButton.setImmediate(true);
		HelpButton.setDescription(" ? ");
		HelpButton.setWidth("-1px");
		HelpButton.setHeight("22px");
		horizontalLayout_1.addComponent(HelpButton);
		horizontalLayout_1.setComponentAlignment(HelpButton, new Alignment(48));

		return horizontalLayout_1;

	}

}
